#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        1.0           \
    window_opacity               on            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on            \
    top_padding                  6             \
    bottom_padding               6             \
    left_padding                 6             \
    right_padding                6             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
# yabai -m rule --add app=".*" manage=off
# yabai -m rule --add app="^Google Chrome$" manage=on
# yabai -m rule --add app="^Kitty$" manage=on

# requires JankyBorders: https://github.com/FelixKratz/JankyBorders
# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &
# generating new border colors:
# https://coolors.co/07020d-5db7de-f1e9db-a39b8b-716a5c
# https://rgbacolorpicker.com/rgba-to-hex

# borders \
#   "active_color=gradient(top_left=0xffffc640,bottom_right=0xffba3aa5)" \
#   "inactive_color=gradient(top_left=0xaa45c4c0,bottom_right=0xaaba3aa5)" \
#   width=10

borders active_color=0xffcba6f7 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
